### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by th3c0d3br34ker**
This PR includes the following changes:

1. Added the `student.py` file with the `Student` class definition.
2. Added the `main.py` file with code demonstrating the use of the "this" pointer.

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
I have done an explanation of this PR [here](https://www.loom.com/share/157b9ac31b60460a9e16a348d7c863b9?sid=d397251a-6d6e-4de1-9b8c-2d06f687719d).

**Comment by anilgulecha** [comment]
Thanks, Jainam, I've reviewed the loom. A good video that covers general viva scope will have:
1) In depth explanation - including walking though the code, and explaining it in all aspects.
2) Explaing what more could be done, but is missing in the current explanation - to showcase indepth understanding
3) a running demo of the project.

You've covered (1) and (2), but (3) is missing. Can you please get this done and let me know again. If that is satisfactory, we can skip the live Viva.

Thanks

**Comment by th3c0d3br34ker** [comment]
Hi Anil, Thanks for your feedback.

Here is a demo of the project [link](https://www.loom.com/share/65956e8f07c3429ba4a35858c995222c?sid=95b957fb-2b48-4d68-a962-ecd70d381706).

**Comment by anilgulecha** [comment]
You can merge it as previously approved orally.

PS: But also, please wait for a written confirmation comment here on the PR before merging.

**Pull request merged**
